[package]
name = "recipes-app"
version = "0.1.0"
authors = ["Evan B <ebensh@gmail.com>"]
edition = "2018"
description = "A website for organizing recipes and planning meals."
repository = "https://github.com/ebensh/recipes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"

# https://rustwasm.github.io/wasm-bindgen/web-sys/using-web-sys.html
[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "HtmlCollection",
  "HtmlElement",
  "Window",
]

# [tasks.build]
# command = "wasm-pack"
# args = ["build", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
